### ISSUE TITLE
Aider Command fails with UnicodeEncodeError: 'charmap' codec can't encode character '\u2588'

### ISSUE THREAD

**Issue by p-wegner** [p-wegner/coding-aider#1]
Sometimes executing an aidercommand seems to work initially, but then after/when applying the search and replace fails with encoding issues. E.g.:
```
To ensure that the `MarkdownDialog` gets focused when the "Test Aider Installation" button is clicked, we need to modify the `AiderSettingsConfigurable.kt` file to call the `focus()` method on the `MarkdownDialog` after it is created.

Here is the *SEARCH/REPLACE* block to implement this change:

src\main\kotlin\de\andrena\codingaider\settings\AiderSettingsConfigurable.kt
```kotlin
<<<<<<< SEARCH
                    button("Test Aider Installation") {
                        AiderTestCommand(project, "aider --help").execute()?.focus()
                    }
=======
                    button("Test Aider Installation") {
                        val dialog = AiderTestCommand(project, "aider --help").execute()
                        dialog?.focus()
                    }
>>>>>>> REPLACE
```
Tokens: 5.8k sent, 170 received. Cost: $0.02 message, $0.02 session.
Applied edit to 
src\main\kotlin\de\andrena\codingaider\settings\AiderSettingsConfigurable.kt
Commit 6442b8c fix: focus the MarkdownDialog when clicking the Test Aider 
Installation button

# Fix any errors below, if possible.

# Uncaught UnicodeEncodeError in cp1252.py line 19

Aider version: 0.55.0
Python version: 3.10.0
Platform: Windows-10-10.0.19045-SP0
Python implementation: CPython
Virtual environment: Yes
OS: Windows 10 (64bit)
Git version: git version 2.45.2.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 7, in <module>
    sys.exit(main())
  File "main.py", line 667, in main
    coder.run(with_message=args.message)
  File "base_coder.py", line 724, in run
    self.run_one(with_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1194, in send_message
    lint_errors = self.lint_edited(edited)
  File "base_coder.py", line 1296, in lint_edited
    self.io.tool_warning(res)
  File "io.py", line 545, in tool_warning
    self._tool_message(message, strip, self.tool_warning_color)
  File "io.py", line 538, in _tool_message
    self.console.print(message, **style)
  File "console.py", line 1683, in print
    with self:
  File "console.py", line 864, in __exit__
    self._exit_buffer()
  File "console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "console.py", line 2024, in _check_buffer
    self._write_buffer()
  File "console.py", line 2060, in _write_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "_windows_renderer.py", line 19, in legacy_windows_render
    term.write_text(text)
  File "_win32_console.py", line 403, in write_text
    self.write(text)
  File "cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2588' in position 40: character maps to <undefined>
```
https://github.com/paul-gauthier/aider/issues/1408

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can use `--encoding` to set the encoding for aider to use.

**Comment by p-wegner** [comment]
Thanks for the hint. I'll try different encodings, but I'm not so sure if this can help. The used Java ProcessBuilder https://github.com/p-wegner/coding-aider/blob/82462a4cd35c314e40a903349fae9b33f2231d1d/src/main/kotlin/de/andrena/codingaider/executors/CommandExecutor.kt#L25
uses the default jvm encoding which is utf-8 for me and i would prefer not to change that. I wonder why this doesn't happen with aider in the shell (without --message option).

**Comment by paul-gauthier** [comment]
You seem to be scripting or wrapping aider inside some other tool. That is probably what is causing the problem.

**Comment by p-wegner** [comment]
I think i found the issue. Some of aiders messages can't be encoded  in cp1252 (ANSI) e.g. the progress indicator character ⠋ for "updating repo map"  . For some reason the way i run the aider process lead to ANSI being used, which was fixed by setting the env variable PYTHONIOENCODING=utf-8. Thanks for your help @paul-gauthier
